spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
# Local
    #password: 0075336
    #url: jdbc:postgresql://localhost:5432/houzing
    #username: postgres
# Remote
    password: 0bdaaf58a90e1c2d57c30944b8388d2449b67c2808f20e0aa6d10b157a98d7e2
    url: jdbc:postgresql://ec2-18-214-35-70.compute-1.amazonaws.com:5432/d8pne2ri4o16j9
    username: nezjhnegwtrqdb
